#!/bin/bash
PROJECT="$1"; PROJECT_ROOT="$2"; TS="$3"
[ -z "$PROJECT" ]      && echo "no project" && exit 1
[ -z "$PROJECT_ROOT" ] && echo "no project root" && exit 1
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PP_ROOT="$(cd "$SELF_DIR/../../.." && pwd)"
LOG_SRC="$PP_ROOT/data/log/doc/src"
SRC_DIR="$PROJECT_ROOT/src"
REF_DIR="$PROJECT_ROOT/docs/ref"
REF_FILE="$REF_DIR/SCRIPTS.md"
mkdir -p "$REF_DIR"
SCRIPT_COUNT=0
cat > "$REF_FILE" << HEADER
# $PROJECT — script reference
> auto-generated by doc_worker/gen_ref.sh on $TS
> do not edit by hand

---

HEADER
if [ ! -d "$SRC_DIR" ]; then
  echo "no src/ dir — ref empty" >> "$REF_FILE"
  bash "$LOG_SRC/on_ref_gen.sh" "$PROJECT" "$REF_FILE" "0" "$TS"
  exit 0
fi
for script in "$SRC_DIR"/*.sh; do
  [ -f "$script" ] || continue
  SCRIPT_COUNT=$((SCRIPT_COUNT + 1))
  FNAME=$(basename "$script")
  DOC=$(grep '^# @doc'     "$script" | sed 's/# @doc *//')
  USAGE=$(grep '^# @usage'  "$script" | sed 's/# @usage *//')
  INPUT=$(grep '^# @input'  "$script" | sed 's/# @input *//')
  OUTPUT=$(grep '^# @output' "$script" | sed 's/# @output *//')
  DOMAIN=$(grep '^# @domain' "$script" | sed 's/# @domain *//')
  STATE=$(grep '^# @state'  "$script" | sed 's/# @state *//')
  TIER=$(grep '^# @tier'   "$script" | sed 's/# @tier *//')
  printf '## %s\n\n' "$FNAME" >> "$REF_FILE"
  [ -n "$DOC" ]    && printf '> %s\n\n' "$DOC"    >> "$REF_FILE"
  [ -n "$USAGE" ]  && printf '**usage:** %s\n\n' "$USAGE"  >> "$REF_FILE"
  [ -n "$INPUT" ]  && printf '**input:** %s\n\n' "$INPUT"  >> "$REF_FILE"
  [ -n "$OUTPUT" ] && printf '**output:** %s\n\n' "$OUTPUT" >> "$REF_FILE"
  [ -n "$DOMAIN" ] && printf '**domain:** %s\n\n' "$DOMAIN" >> "$REF_FILE"
  [ -n "$STATE" ]  && printf '**state:** %s\n\n' "$STATE"  >> "$REF_FILE"
  [ -n "$TIER" ]   && printf '**tier:** %s\n\n' "$TIER"   >> "$REF_FILE"
  printf '---\n\n' >> "$REF_FILE"
done
echo "[$PROJECT] gen_ref: $SCRIPT_COUNT scripts → $REF_FILE"
bash "$LOG_SRC/on_ref_gen.sh" "$PROJECT" "$REF_FILE" "$SCRIPT_COUNT" "$TS"
